apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-web-dpl
  labels:
   appd: shop-webd
spec:
  replicas: 1
  selector:
    matchLabels:
     version: v1
  template:
    metadata:
      labels:  
        app: shop-web 
        version: v1
    spec:
      containers:
      - name: shop-web
        image: devopseasylearning2021/s3-project01-espresso-shop:v1.0.0
        imagePullPolicy: Always
        env:
        - name: ProductCatalogUrl
          valueFrom:
            configMapKeyRef: 
             name: cfm
             key: ProdUrl
        - name: ReviewsUrl
          valueFrom:
            configMapKeyRef: 
             name: cfm
             key: RevUrl
        ports:
          - containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: shop-web-svc
spec:
  selector: 
    version: v1
    app: shop-web
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 80
  type: LoadBalancer







