apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-product
  labels:
    app: shop-product
spec:
  replicas: 0
  selector:
    matchLabels:
      app: shop-product
  template:
    metadata:
      labels: 
        version: v1
        app: shop-product
    spec:
      containers:
      - name: shop-product
        image: devopseasylearning2021/s3-project01-espresso-shop-product:v1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shop-product
spec:
  selector:
    app: shop-product
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 80
