apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-review1-dpl
  labels:
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      version: v2
  template:
    metadata:
      labels: 
        version: v2
        app: shop-review2
    spec:
      containers:
      - name: shop-review1
        image: devopseasylearning2021/s3-project01-espresso-shop-review:v1.0.0
        env:
        - name: SERVICE_VERSION
          valueFrom:
            configMapKeyRef: 
             name: cfm
             key: sv1
        ports:
          - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-review2-dpl
  labels:
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      version: v2
  template:
    metadata:
      labels: 
        version: v2
        app: shop-review2
    spec:
      containers:
      - name: shop-review2
        image: devopseasylearning2021/s3-project01-espresso-shop-review:v1.0.0
        env:
        - name: SERVICE_VERSION
          valueFrom:
            configMapKeyRef: 
             name: cfm
             key: sv2
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shop-reviews-svc
spec:
  selector:
    version: v2
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 80
