apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-review1
  labels:
    app: shop-reviews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-reviews
  template:
    metadata:
      labels: 
        version: v1
        app: shop-reviews
    spec:
      containers:
      - name: shop-reviews
        image: devopseasylearning2021/s3-project01-espresso-shop-review:v1.0.0
        env:
        - name: SERVICE_VERSION
          valueFrom:
            configMapKeyRef: 
             name: cfm
             key: sv1
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-review2
  labels:
    app: shop-reviews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-reviews
  template:
    metadata:
      labels: 
        version: v2
        app: shop-reviews
    spec:
      containers:
      - name: shop-reviews
        image: devopseasylearning2021/s3-project01-espresso-shop-review:v1.0.0
        env:
        - name: SERVICE_VERSION
          valueFrom:
            configMapKeyRef: 
             name: cfm
             key: sv2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shop-reviews
spec:
  selector:
    app: shop-reviews
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 80
