apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-product-deploy
  labels:
    app: shop-product
spec:
  replicas: 2
  selector: # to set up the deployment selector
    matchLabels:
      app: shop-product
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template: # pods label
    metadata:
      labels:
        app: shop-product
        version: v1
    spec:
      containers:
        - name: shop-product
          image: "devopseasylearning2021/s3-project01-espresso-shop-product:v1.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-product-catalog-svc
spec:
  type: ClusterIP
  selector:
    app: shop-product
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 80